"""
Developer Agent module.

This module defines the DeveloperAgent, a specialized AI agent responsible
for implementing software solutions from implementation plans.

The agent receives an implementation plan produced by the PlannerAgent,
builds a contextual prompt using the developer role instructions, and
delegates text generation to the functionality provided by BaseAgent.
"""

from time import perf_counter
import json
from pathlib import Path

from ai_dev_team.agents.base import BaseAgent
from ai_dev_team.prompts.developer import DEVELOPER_SYSTEM_PROMPT
from ai_dev_team.prompts.developer_tools import (
    DEVELOPER_TOOLS_PROMPT,
    DEVELOPER_INCOMPLETE_PROMPT,
)
from ai_dev_team.tools.workspace import GeneratedWorkspace


class DeveloperAgent(BaseAgent):
    """
    AI agent specialized in implementing software from implementation plans.
    """

    def __init__(self, llm_provider, output_dir: Path, max_iterations: int = 12):
        super().__init__(llm_provider)
        if max_iterations < 1:
            raise ValueError('max_iterations must be positive.')
        self.workspace = GeneratedWorkspace(output_dir)
        self.max_iterations = max_iterations

    def run(self, task: str) -> str:
        """
        Generate a software implementation from the given implementation plan.

        Args:
            task: Implementation plan describing the software to build.

        Returns:
            The source code generated by the language model.
        """
        start_time = perf_counter()
        messages = [
            {'role': 'system', 'content': DEVELOPER_SYSTEM_PROMPT + '\n' + DEVELOPER_TOOLS_PROMPT},
            {'role': 'user', 'content': task},
        ]
        available = {name: getattr(self.workspace, name) for name in
                     ('list_files', 'read_file', 'write_file', 'check_syntax',
                      'check_static_analysis')}
        # Keep failed writes pending so old valid files cannot count as a completed revision.
        pending_writes = {}
        try:
            for iteration in range(self.max_iterations):
                print(f'DeveloperAgent iteration {iteration + 1}/{self.max_iterations}', flush=True)
                message = self.llm_provider.chat(messages, list(available.values()))
                messages.append(message)
                print(f'DeveloperAgent response: {len(message.tool_calls or [])} tool call(s), '
                      f'{len(message.content or "")} text characters.', flush=True)
                if message.content:
                    print('DeveloperAgent response preview (not saved as a file):', flush=True)
                    print(message.content[:1500], flush=True)
                    if len(message.content) > 1500:
                        print('[Preview truncated to 1500 characters]', flush=True)
                if message.tool_calls:
                    # Bound tool execution as well as model turns.
                    for index, call in enumerate(message.tool_calls):
                        name = call.function.name
                        arguments = dict(call.function.arguments)
                        if 'content' in arguments:
                            arguments['content'] = f'<{len(str(arguments["content"]))} characters>'
                        print(f'DeveloperAgent tool starting: {name} '
                              f'{json.dumps(arguments)}', flush=True)
                        try:
                            if index >= 8:
                                raise ValueError('At most 8 tool calls are allowed per turn.')
                            if name not in available:
                                raise ValueError(f'Unknown tool: {name}')
                            result = available[name](**call.function.arguments)
                            if name == 'write_file':
                                path = str(call.function.arguments.get('path'))
                                pending_writes.pop(path, None)
                        except (ValueError, TypeError, OSError) as exc:
                            result = {'error': str(exc)}
                            if name == 'write_file':
                                path = str(call.function.arguments.get('path'))
                                pending_writes[path] = str(exc)
                        displayed = json.dumps(result)
                        if name == 'read_file' and isinstance(result, str):
                            displayed = f'Read {len(result)} characters.'
                        print(f'DeveloperAgent tool result: {name}: {displayed}', flush=True)
                        messages.append({'role': 'tool', 'tool_name': name,
                                         'content': json.dumps(result)})
                    continue
                print('DeveloperAgent: no tool calls; checking saved files before completion.', flush=True)
                check = {'syntax': self.workspace.check_syntax(),
                         'static_analysis': self.workspace.check_static_analysis(),
                         'pending_writes': pending_writes}
                print(f'DeveloperAgent final checks: {json.dumps(check)}', flush=True)
                if (check['syntax']['ok'] and check['static_analysis']['ok']
                        and not pending_writes):
                    print(f'DeveloperAgent completed: {self.workspace.root}', flush=True)
                    return self.workspace.source()
                print('DeveloperAgent: checks failed; sending diagnostics back to the model.', flush=True)
                messages.append({'role': 'user', 'content':
                                 DEVELOPER_INCOMPLETE_PROMPT + json.dumps(check)})
            raise RuntimeError(
                f'Developer did not finish within {self.max_iterations} iterations. '
                f'Partial files remain in {self.workspace.root}.')
        finally:
            elapsed_time = perf_counter() - start_time
            print(f'DeveloperAgent execution time: {elapsed_time:.2f} seconds')
