"""
Developer Agent module.

This module defines the DeveloperAgent, a specialized AI agent responsible
for implementing software solutions from implementation plans.

The agent receives an implementation plan produced by the PlannerAgent,
builds a contextual prompt using the developer role instructions, and
delegates text generation to the functionality provided by BaseAgent.
"""

from ai_dev_team.agents.base import BaseAgent
from ai_dev_team.prompts.developer import DEVELOPER_SYSTEM_PROMPT


class DeveloperAgent(BaseAgent):
    """
    AI agent specialized in implementing software from implementation plans.
    """

    def run(self, task: str) -> str:
        """
        Generate a software implementation from the given implementation plan.

        Args:
            task: Implementation plan describing the software to build.

        Returns:
            The source code generated by the language model.
        """
        prompt = f"""
{DEVELOPER_SYSTEM_PROMPT}

Implementation Plan:

{task}

Generate the complete Python implementation.
"""

        return self.generate(prompt)