"""
Developer Agent module.

This module defines the DeveloperAgent, a specialized AI agent responsible
for generating software implementations from natural language requirements.

The agent builds a contextual prompt using the developer role instructions
and delegates text generation to the functionality provided by BaseAgent.
"""

from ai_dev_team.agents.base import BaseAgent
from ai_dev_team.prompts.developer import DEVELOPER_SYSTEM_PROMPT


class DeveloperAgent(BaseAgent):
    """
    AI agent specialized in software development tasks.
    """

    def run(self, task: str) -> str:
        """
        Generate a software implementation for the given task.

        Args:
            task: Natural language description of the requested implementation.

        Returns:
            The solution generated by the language model.
        """
        prompt = f"""
{DEVELOPER_SYSTEM_PROMPT}

Task:
{task}
"""

        return self.generate(prompt)