"""
Planner Agent module.

This module defines the PlannerAgent, a specialized AI agent responsible for
analyzing software development requests and producing implementation plans.

The agent builds a contextual prompt using the planner role instructions and
delegates text generation to the functionality provided by BaseAgent.
"""

from time import perf_counter

from ai_dev_team.agents.base import BaseAgent
from ai_dev_team.prompts.planner import PLANNER_SYSTEM_PROMPT


class PlannerAgent(BaseAgent):
    """
    AI agent specialized in software planning.

    The PlannerAgent transforms software requirements into a structured
    implementation plan before development begins.
    """

    def run(self, task: str) -> str:
        """
        Generate an implementation plan for the given software task.

        Args:
            task: Natural language description of the requested software.

        Returns:
            A structured implementation plan generated by the language model.
        """
        start_time = perf_counter()
        prompt = f"""
{PLANNER_SYSTEM_PROMPT}

Task:
{task}
"""

        result = self.generate(prompt)
        elapsed_time = perf_counter() - start_time
        print(f"PlannerAgent execution time: {elapsed_time:.2f} seconds")
        return result
